version: '3.9'

services:

    ravendb:
        image: ravendb/ravendb:latest
        ports:
            - 8080:8080

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 0b6273775d
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
